
server:
  address: localhost
  port: 9010

spring:
  application:
    name: notifications

  cloud:
    function:
      definition: email|sms

    stream:
      bindings:
        emailsms-in-0:
          destination: send-notifications
          group: ${spring.application.name}

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 1234

  #mail:
  #  host: smtp.gmail.com
  #  port: 587
  #  username: ${SMTP_USERNAME}
  #  password: ${SMTP_PASSWORD}
  #  properties:
  #    mail:
  #      smtp:
  #        auth: true
  #        starttls:
  #          enable: true

