spring:
  application:
    name: notifications

  cloud:
    function:
      definition: email|sms

    stream:
      bindings:
        email-sms-in-0:
          destination: send-notifications
          group: ${spring.application.name}
      binders:
        rabbit:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

