spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics

  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

  tracing:
    enabled: true
    sampling:
      probability: 1