spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/, classpath:/config, file:./, file:./config"

server:
  port: 8888
  address: 0.0.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always