services:
  ms-parent-service:
    environment:
      SPRING_PROFILES_ACTIVE: qa
    networks:
      - bank-ms-net
    restart: always

  business-ms-parent:
    extends:
      service:
        ms-parent-service
    depends-on:
      eureka-server-ms:
        condition: service_healthy