services:
  postgres-parent-service:
    image: postgres
    networks:
      - bank-ms-net
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5


  pgAdmin:
    image: 'dpage/pgadmin4'
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=mohamecabdelaziz66@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - '5050:80'
    depends_on:
      - postgres-accounts
      - postgres-cards
      - postgres-loans
    restart: always
    networks:
      - bank-ms-net

