
services:

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rmq-cont
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - 'rmq-data:/var/lib/rabbitmq'
    networks:
      - bank-ms-net
    environment:
       RABBITMQ_DEFAULT_USER: admin
       RABBITMQ_DEFAULT_PASS: 1234

  postgres-keycloak:
    extends:
      file: common.yml
      service: postgres-parent-service
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  keycloak:
    image: docker.io/bitnami/keycloak:25.0.2
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_DATABASE_VENDOR: postgres
      KEYCLOAK_DATABASE_HOST: localhost
      KEYCLOAK_DATABASE_PORT: 5435
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: admin
      KEYCLOAK_DATABASE_PASSWORD: 1234
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: 1234
    ports:
      - "5000:8080"
    depends_on:
      postgres-keycloak:
        condition: service_healthy

  #keycloak:
  #  image: quay.io/keycloak/keycloak:26.4.1
  #  ports:
  #    - "5000:8080"
  #  environment:
  #     KC_BOOTSTRAP_ADMIN_USERNAME: admin
  #     KC_BOOTSTRAP_ADMIN_PASSWORD: 1234
  #     KC_DB_URL: jdbc:postgresql://localhost:5432/keycloak
  #     KC_DB_USERNAME: admin
  #     KC_DB_PASSWORD: 1234
  #  depends_on:
  #    postgres-keycloak:
  #      condition: service_healthy
  #  command: "start-dev"

  postgres-accounts:
    environment:
      POSTGRES_DB: accounts-db
    ports:
      - '5432:5432'
    volumes:
      - accounts-db-data:/var/lib/postgresql/data
    extends:
      file: common.yml
      service: postgres-parent-service

  postgres-cards:
    environment:
      POSTGRES_DB: cards-db
    ports:
      - '5433:5432'
    volumes:
      - cards-db-data:/var/lib/postgresql/data
    extends:
      file: common.yml
      service: postgres-parent-service
    networks:
      - bank-ms-net

  postgres-loans:
    environment:
      POSTGRES_DB: loans-db
    ports:
      - '5434:5432'
    volumes:
      - loans-db-data:/var/lib/postgresql/data
    extends:
      file: common.yml
      service: postgres-parent-service
    networks:
      - bank-ms-net

  pgadmin:
    extends:
      file: common.yml
      service: pgAdmin

volumes:
  accounts-db-data:
  cards-db-data:
  loans-db-data:
  rmq-data:
  keycloak-data:

networks:
  bank-ms-net:
    driver: bridge
