
spring:
  application:
    name: accounts
  config:
    import: "optional:configserver:http://localhost:8888/"

  cloud:
    stream:
      bindings:
        sendEmail-out-0:                   # unified naming conv
          destination: send-notifications  # exchange name

  rabbitmq:
    username: admin
    password: 1234
    host: localhost
    port: 5672



