
spring:

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 4
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state:
          seconds: 4

microservices:
  cards:
    url: "http://localhost:8090"
  loans:
    url: "http://localhost:9000"
