spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username: admin
    password: 1234
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka/"

