spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8085

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: "${EUREKA_URL:http://localhost:8761}/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    accounts-circuit-breaker:
      slidingWindowSize: 5
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permitted-number-of-calls-in-half-open-state: 2

      cards-circuit-breaker:
        slidingWindowSize: 5
        failureRateThreshold: 60
        waitDurationInOpenState: 15s
        permitted-number-of-calls-in-half-open-state: 2

